Travis-CI: Fix ImportError: No module named 'zipp' (#502)
Upgrade pip to fix [*]:

  [66/66] Linking target example/passthrough_hp.
  Traceback (most recent call last):
    File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
      mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
    File "/usr/lib/python3.5/runpy.py", line 133, in _get_module_details
      return _get_module_details(pkg_main_name, error)
    File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
      __import__(pkg_name)
    File "/usr/local/lib/python3.5/dist-packages/pytest/__init__.py", line 6, in <module>
      from _pytest.assertion import register_assert_rewrite
    File "/usr/local/lib/python3.5/dist-packages/_pytest/assertion/__init__.py", line 7, in <module>
      from _pytest.assertion import rewrite
    File "/usr/local/lib/python3.5/dist-packages/_pytest/assertion/rewrite.py", line 24, in <module>
      from _pytest.assertion import util
    File "/usr/local/lib/python3.5/dist-packages/_pytest/assertion/util.py", line 14, in <module>
      import _pytest._code
    File "/usr/local/lib/python3.5/dist-packages/_pytest/_code/__init__.py", line 2, in <module>
      from .code import Code  # noqa
    File "/usr/local/lib/python3.5/dist-packages/_pytest/_code/code.py", line 28, in <module>
      import pluggy
    File "/usr/local/lib/python3.5/dist-packages/pluggy/__init__.py", line 16, in <module>
      from .manager import PluginManager, PluginValidationError
    File "/usr/local/lib/python3.5/dist-packages/pluggy/manager.py", line 11, in <module>
      import importlib_metadata
    File "/usr/local/lib/python3.5/dist-packages/importlib_metadata/__init__.py", line 9, in <module>
      import zipp
  ImportError: No module named 'zipp'
  The command "test/travis-build.sh" exited with 1.

[*] https://travis-ci.org/libfuse/libfuse/builds/651523034

Signed-off-by: Philippe Mathieu-Daudé <philmd@redhat.com>
(cherry picked from commit 29b71ac481cb597355cec60770cf32d4173b8fd9)